name: smart-traffic-management
services:
- name: web
  github:
    repo: Shriram2005/Smart-Traffic-Management
    branch: main
  build_command: pip install -r requirements.txt
  run_command: python main.py
  http_port: 5000
  health_check:
    http_path: /
  envs:
  - key: FLASK_ENV
    value: production
  - key: FLASK_PORT
    value: "5000"
